### ISSUE TITLE
Typo in repository name

### ISSUE THREAD

**Issue by krassowski** [reimandlab/Visualisation-Framework-for-Genome-Mutations#10]
I have just discovered a typo in the repository name "Visualistion" should "Visualis**a**tion". I cannot access the settings, but it should be easy to change - on the bar under the title [there should be a "Settings" tab](https://help.github.com/articles/renaming-a-repository/) (the last one). @reimand0, could you help me with that one?

**Comment by reimand0** [comment]
done. Thanks for noticing!
