### ISSUE TITLE
user input as collection of variants

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#16]
One necessary way of inputting data is by chromosome coordinates of genome variants (chr, pos, ref, alt). For example VCF and MAF files have that information. The user can have one or many (MANY) from a genome sequencing study he or she performed. Some of these variants can be in the dataset more than one time, then a count should be shown. 

We should convert these DNA coordinates to protein coordinates and show protein-level mutations as a table and links to protein views. Non-mapping coordinates should be excluded and a line of text will say how many were excluded. There is a filter that allows to only show PTM-site mutations (default=ON).

As the number of variants is large, we may need to store the information on server sideand allow the user to retrieve the session for a limited time.

**Comment by reimand0** [comment]
Let's use a mixed format so that both genome and protein changes can be reflected in the  same input. We can use the following format that distinguishes DNA-level (four columns) and protein-level mutations (two columns)

chr1 1234567 A T # a DNA-level mutation
TP53 R282W # a protein level mutation

**Comment by reimand0** [comment]
Also, just making a note here that mutations can be uploaded with several duplicate entries. These should be counted and displayed according to counts.

**Comment by reimand0** [comment]
Finally, let's add an example input that people can analyse. 

1. link "load example" will copy an example to the input field.
2. clicking on "search" will run that example quickly.

**Comment by krassowski** [comment]
Added a a filter that allows to only show PTM-site mutations.
