### ISSUE TITLE
REST service for exporting mutations

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#18]
We should have a web service interface to get mutations from the database. The output should contain protein mutations, status relative to PTM sites, MIMP status, mutation counts (cancer) or allele frequencies (population), further meta-information (cancer type, disease name, population subgroup name). 

potential input queries to discuss
1. protein mutation - NM_000123 A12R
2. DNA mutation - chr1 123456 A T
3. all mutations in gene - NM_000123
4. all mutations in gene and dataset - NM_000123 ESP6500
5. all mutations in range of DNA coordinates - chr1 123456 223456

**Comment by krassowski** [comment]
Seems good. Only thing which would require more work is point 5. - it would require creating additional instance of mappings BerkleyDB with some structure of a range tree as index (along with already used refseq and position hash).

**Comment by reimand0** [comment]
OK. Let's set #5 to lower priority. if it turns out to be slow or
complicated we could instead use a dataset with gene coordinates. Then
genes in the range will be analysed for protein-level mutations. Only the
genes on the edges of the range will be problematic if the range limit runs
through the middle of a gene.

**Comment by krassowski** [comment]
so the third point is already here:
`https://rl-db.oicr.on.ca/protein/mutations/NM_000546`
and forth also:
`https://rl-db.oicr.on.ca/protein/mutations/NM_001904?filters=Mutation.sources:in:ESP6500`.

I will start writing some documentation.

**Comment by reimand0** [comment]
That's great, thanks! 

We should probably discuss some of these use cases with nearby biologists

**Comment by reimand0** [comment]
just curious - once we resolve points 1 and 2, can a researcher use a script to pull information about a set of 100s-1000s variants? Just like the current VCF upload window.

**Comment by krassowski** [comment]
So we have points 1, 2, 4 implemented and described here: https://github.com/reimandlab/Visualisation-Framework-for-Genome-Mutations/wiki/REST-API. I will need to make some more changes to retrieve mutations from different datasets at once - i.e. to implement point 3 - it's technically possible now, but the results needs some more tweaking.

> just curious - once we resolve points 1 and 2, can a researcher use a script to pull information about a set of 100s-1000s variants? Just like the current VCF upload window.

I think there should be no problems with this.

Question regarding implementation of point 5: we have two options to implement this:
1) use some special structure of database (some kind of tree) that will support range queries
2) have the whole reference chromosomal sequence and do single nucleotide checks, one by one using this what we already have. To do so I'll need to know which assembly of human genome do we use. (I think that we discussed this a long time ago but I cannot recollect right now). Could you provide me with this information?

**Comment by reimand0** [comment]
Let's leave (5) aside by now. However can one also retrieve all mutations in gene and cancer type (population type), or perhaps just all mutations in one dataset+cancer type? 

a) NM_000123 TCGA GBM
b) TCGA GBM

I plan to start a practical project with Marta Pączkowska that uses this API. She is a visiting researcher from the University of Warsaw. I will put you two in touch soon.

**Comment by reimand0** [comment]
For usability purposes, the documentation should have a few practical copy-paste examples. For example, input chromosomal coordinate - output real example of PTM mutation X. You can take one known example from TP53 for this purpose.

**Comment by krassowski** [comment]
I improved the results returned. Does it looks better now?

**Comment by reimand0** [comment]
Yes, more information is better. However, we are still not covering all
mutations:

this works - https://rl-db.oicr.on.ca/protein/known_mutation/NM_000546/77/L
this does not - *https://rl-db.oicr.on.ca/protein/known_mutation/NM_000546/76/L
<https://rl-db.oicr.on.ca/protein/known_mutation/NM_000546/76/L>*

Is this because 76L is not present in TCGA or because 76th residue cannot
change to L because of genetic code?

**Comment by krassowski** [comment]
The first one (it's not present in TCGA). My bad, I have focused on the "chormosome" (genomic) endpoint and left this one out. I will change the name of the endpoint `protein/known_mutation` to `protein/mutation`, improve the returned results, include novel mutations and make it return data for all datasets.

**Comment by krassowski** [comment]
I amended the protein endpoint. Is this know working as expected?

https://rl-db.oicr.on.ca/protein/mutation/NM_000546/76/L
https://rl-db.oicr.on.ca/protein/mutation/NM_000546/77/L
https://rl-db.oicr.on.ca/chromosome/mutation/chr1/115256530/G/T

**Comment by reimand0** [comment]
Thanks! Let's close this for now. Depending on the mutation mapping with
Marta, we may open another issue for additional features.
