### ISSUE TITLE
PTM sites by color

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#26]
We have four types of PTM sites. These are now shown as green blocks in needleplot. We should use colors to distinguish the different types of PTM sites.

dark blue - phosphorylation
dark green - ubiquitination
light blue - acetylation
light green - methylation

**Comment by krassowski** [comment]
What about more complicated cases, when we have a site which is both acetylation and methylation?

This is full list of cases we have to cover:
{'acetylation',
 'acetylation,methylation',
 'acetylation,methylation,ubiquitination',
 'acetylation,phosphorylation',
 'acetylation,ubiquitination',
 'methylation',
 'methylation,ubiquitination',
 'phosphorylation',
 'ubiquitination'}

**Comment by reimand0** [comment]
Correct. Let's add a 5th class to denote multiPTM sites. 

Let me reconfigure the colors here. I selected five colors from color brewer. let's make the darkest color a multiPTM site and lighter colors in the order of site abundance (phospho - darkest - most sites) to (methylation - lightest - fewest sites). 

[ColorBrewer - Selecting Good Color Schemes for Maps.pdf](https://github.com/reimandlab/Visualisation-Framework-for-Genome-Mutations/files/422981/ColorBrewer.-.Selecting.Good.Color.Schemes.for.Maps.pdf)
![screen shot 2016-08-17 at 11 55 25 am](https://cloud.githubusercontent.com/assets/19268349/17743509/f1070580-6471-11e6-9f38-c38db71ea0a7.png)

**Comment by krassowski** [comment]
Ok, the number of occurrences are:

> 'phosphorylation': 299241,
> 'ubiquitination': 67933,
> 'acetylation': 21670,
> 'methylation': 5666

hence 'ubiquitination': 0x7bccc4 gets and 'acetylation': 0xbae4bc, is that correct?

**Comment by krassowski** [comment]
I am afraid that the weakest color is hardly distinguishable from background: https://rl-db.oicr.on.ca/protein/show/NM_000546. Also it does not indicate where sites of different types overlap - one solution would be to add semi transmittance (but it wont work with this color schema), another idea would be to add some ticks on beginning and end of a site.

**Comment by reimand0** [comment]
Ticks or a box around a site might work

Jüri
