### ISSUE TITLE
filtering of PTM sites

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#30]
we should be able to filter which PTM sites are considered in the analysis of mutations. By default, all PTMs are included, but the user can choose one PTM or several PTMs to be included. 

This filtering should change needleplot, table and any other aspects of the website.

**Comment by reimand0** [comment]
Thanks! Looking at protein sequence view with only Ubiquitination selected in TP53, the needles do not change their color accordingly. Also the table is not reflecting the filter of PTM classes.

**Comment by krassowski** [comment]
Should "# PTMs affected" columns also be affected by sites filter? I mean, should it show total number of such sites or count only those which are from selected category?

**Comment by reimand0** [comment]
Yes, it would be good to have everything consistent according to selected
filters.
