### ISSUE TITLE
filtering of mutations

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#31]
we should be able to filter mutations by cancer type and population subgroups. 

First, a user selects the dataset of mutations that are used (four datasets - TCGA cancer, ESP6500 population, 1000G population, ClinVar). 

Second, a new filtering panel becomes available that shows cancer types or population subgroups. This could be a multiple choice form. By default, all types/subgroups are active.

I think ClinVar currently has no such grouping, but I will look at the data and see if it makes sense to add one option like this. For example, maybe there are high-quality and low-quality mutations in clinvar.

**Comment by reimand0** [comment]
following up on this - clinvar has a field to filter by clinical significance

 ##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Variant Clinical Significance, 0 - Uncertain significance, 1 - not provided, 2 - Benign, 3 - Likely benign, 4 - Likely pathogenic, 5 - Pathogenic, 6 - drug response, 7 - histocompatibility, 255 - other">

**Comment by krassowski** [comment]
Did you mean:
`##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Variant Clinical Significance, 0 - Uncertain significance, 1 - not provided, 2 - Benign, 3 - Likely benign, 4 - Likely pathogenic, 5 - Pathogenic, 6 - drug response, 7 - histocompatibility, 255 - other">`?

**Comment by reimand0** [comment]
Yes i just pasted this from VCF. The bracket tags looked strange in the github comment form

Jüri

**Comment by reimand0** [comment]
Can we add a filter above the needleplot that allows to select cancer types whose mutations are shown:

blca	bladder urothelial carcinoma
brca	breast invasive carcinoma
coadread	colon,rectum adenocarcinoma
gbm	glioblastoma multiforme
hnsc	head and neck squamous cell carcinoma
kirc	kidney renal clear cell carcinoma
laml	acute myeloid leukemia
luad	lung adenocarcinoma
lusc	lung squamous cell carcinoma
ov	ovarian serous cystadenocarcinoma
ucec	uterine corpus endometrioid carcinoma
