### ISSUE TITLE
visualising MIMP mutations

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#33]
Here's an example with MIMP mutations.

In R, this is how we see the top MIMP-mutation in TP53 (they are ordered by prob)
all_mimp_annotations[all_mimp_annotations[,1]=="NM_000546",][1,]

```
         gene               mut         psite_pos          mut_dist
  "NM_000546"           "N310R"             "313"              "-3"
           wt                mt          score_wt          score_mt
```

"RALPNNTSSSPQPKK" "RALPRNTSSSPQPKK"      "0.12003083"      "0.92115458"
        log_ratio               pwm           pwm_fam             nseqs
      " 2.940038"           "CHEK1"      "CAMKL_CHK1"             "104"
             prob            effect
      "0.9971076"            "gain"

Let's imagine that a user uploads the mutation N310R. In column psite_pos, there is the PTM site that gets affected (313) and the kinase whose binding site is affected is shown in column pwm (CHEK1). Below is the logo for CHEK1. 
![screen shot 2016-08-23 at 3 19 34 pm](https://cloud.githubusercontent.com/assets/19268349/17906384/092325f4-6945-11e6-88d7-0a646af900b2.png)

you can see that creating an R-residue to the site creates all the necessary information for the kinase to find its site. The column mut_dist also shows that the mutation N310R is -3 steps away from the site at 313. 

So if R is added, we have a _gain of motif_. We could indicate this GAIN in the logo with a light green box around R. 

So looking at the second example, we have a _loss of motif_. 

all_mimp_annotations[all_mimp_annotations[,1]=="NM_000546",][2,]
             gene               mut         psite_pos          mut_dist
      "NM_000546"           "Q100F"             " 99"              " 1"
               wt                mt          score_wt          score_mt
"PLSSSVPSQKTYQGS" "PLSSSVPSFKTYQGS"      "0.94418516"      "0.11160907"
        log_ratio               pwm           pwm_fam             nseqs
      "-3.080616"           "PRKDC"      "PIKK_DNAPK"             " 67"
             prob            effect
      "0.9970976"            "loss"

![screen shot 2016-08-23 at 3 24 48 pm](https://cloud.githubusercontent.com/assets/19268349/17906531/c0f6ccda-6945-11e6-8204-f233e3e03fe8.png)

the mutation Q100F would be very important in destroying the motif, because Q is a key residue in the motif (+1 steps away from the central residue at position 99). 

We could indicate LOSS in the logo by drawing a red box around position +1 and drawing a top-left-to-bottom-right diagonal through the box.

**Comment by krassowski** [comment]
Should those logos occupy separate column in mutations-search results or should they be shown only after expanding a row mapping to some MIMP annotated mutation (like in protein view)?

**Comment by krassowski** [comment]
Should those logos occupy separate column in mutations-search results or should they be shown only after expanding a row mapping to some MIMP annotated mutation (like in protein view)?

**Comment by reimand0** [comment]
opening separately in protein view is enough. 

However it would be useful to see mutation impact. Instead of network-rewiring, maybe call these 
Motif gain
Motif loss

**Comment by reimand0** [comment]
Adding to this comment - let's keep both "network-rewiring" and more specific description ("motif gain" or "motif loss")

**Comment by reimand0** [comment]
thanks!
