### ISSUE TITLE
table rows colored according to mutation impact

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#37]
Let's change the colors of table rows according to the impact of mutations shown in needle plots - yellow-orange-red-darkred-gray. We should probably tune all the colors to be a lighter so that the table remains easy to read.

**Comment by reimand0** [comment]
for consistency, perhaps we can compute a new lighter color variant for every existing color. this might help - http://www.hexcolortool.com/

**Comment by krassowski** [comment]
All the colors were lightened programmatically by 25%. It works and makes the table readable, but It doesn't look very good to my. Some other idea would be to add a column where cells in each row would be filled with an unaltered color representing mutation impact (just a thought, not necessarily better then existing solution).

**Comment by reimand0** [comment]
OK, let's just color one column "mutation type" according to the color.

Also, the "mutation type" column needs to reflect deeper information -
PTM, direct;
PTM, network-rewiring (MIMP)
PTM, proximal
PTM, distal

**Comment by krassowski** [comment]
In the topic of mutation type column: The columns with details are already here as specified in #3 (6 and 7). They are hidden by default if PTM filter is off and shown be default if it is on (I think it was discussed elsewhere), but this behavior could be abandoned. Should I change something with configuration of these columns?

**Comment by reimand0** [comment]
Yes, let's show this information all the time, as PTM-mutation
relationships are the main feature of this database.

I think we can merge the two columns and show the info in just one column.
Sorting will still work as expected, right?

Thanks,
Jüri

**Comment by krassowski** [comment]
Yes, sorting still works. Is this good enough now?

**Comment by reimand0** [comment]
Yes, I like it.

Also, the PTM filter above is probably better as a checkbox

[ x ] show only PTM mutations (not selected by default)
