### ISSUE TITLE
mutation info in table and tooltip

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#39]
we should have a link in the mutation table (and mutation tooltip) that will expand the row in the mutation table and provide more information about the mutation. The information is already shown in the tooltip. When user clicks on tooltip, the page will scroll down and expand the information in the table row. 

Alternatively, we can open a new page but this will make the page slower, especially when the user wants to go back and forth between many mutations.

**Comment by reimand0** [comment]
We should also have the MIMP logo visible when opening the table for any given mutation

**Comment by reimand0** [comment]
Two more small requests here: 

1. when looking at a table, we need to click + to open the detailed record. Can we click anywhere in the row to open the detailed record?
2. when looking at a record with MIMP logo, it should display whether this MIMP mutation is motif gain or motif loss

**Comment by reimand0** [comment]
More requests on the records - can we show kinases that are binding nearby sites? I don't mean MIMP results, but experimentally confirmed kinases. Thanks!

**Comment by krassowski** [comment]
In tooltips or in the table? If in the table, then as a separate column or after expanding a row?

**Comment by reimand0** [comment]
in table as column, and also as tooltip.

**Comment by krassowski** [comment]
I implemented basic functionality, right now only in table. So, having this: https://rl-db.oicr.on.ca/protein/show/NM_000546 as an example, could we specify if:

- should kinase groups be displayed in the same manner as "normal" kinases (they are right now in the "demo" implementation)
- should we provide more details for each kinase? (we can give following: site details and all protein information if we managed to associate the kinase with protein entry)
- if we have a protein associated with a kinase, maybe it's worth making it clickable (as a link to it's protein view?)
- are there other considerations I have not taken into account yet?

**Comment by reimand0** [comment]
>
>
>    - should kinase groups be displayed in the same manner as "normal"
>    kinases (they are right now in the "demo" implementation)
>
>
a different color is good. Also we can use the same color for kinases that
we cannot link to proteins.


>
>    - should we provide more details for each kinase? (we can give
>    following: site details and all protein information if we managed to
>    associate the kinase with protein entry)
>
>  kinase name, number of muts (PTM muts), number of PTM sites, cancer types
mutated (or populations, or diseases)

**Comment by krassowski** [comment]
This is already implemented and will be deployed to the server with closest opportunity.
