### ISSUE TITLE
site/mutation visual by color

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#4]
Let's visualise PTM sites and mutations by their impact. 

site with mutation - dark blue 
site without mutation - light blue

non-PTM mutation - gray
PTM mutation, direct - red
PTM mutation, flank proximal - orange
PTM mutation, flank distal - yellow

**Comment by krassowski** [comment]
Assuming we have mutation at S13 and sites as described in #2:

> site1 at S13 
> site2 at S15
> 
> region1 is 13-7 until 13+7
> region2 is 15-7 until 15+7
> region_merged is 13-7 until 15+7

Am I correct assuming that region1 and region2 should be merged (regardless of the mutations occurrence) and the whole resulting region should be colored like a site with mutation (dark blue)?

**Comment by reimand0** [comment]
Yes, thats correct. Ps - testing reply with email.

Jüri

**Comment by krassowski** [comment]
Ok. Should this color code be applied to sequence tracks or to the needleplot? I think that sites should be marked and colored on the needleplot the same as on the sequence track below. How about the mutations? Should I create needles/lollipops by grouping mutations by PTM influence or just apply the color code to the mutations listed on the tracks?

Ps. I updated version deployed to http://krassowski.pythonanywhere.com/ - there are no changes affecting current issues but some bugfixes and improvements so debugging and development will be much easier later.

**Comment by reimand0** [comment]
Let's match sequence track colors with needle plot colors. We need to make sure this remains easy to understand. Mutations should be colored by influence on PTMs.

Two further changes coming in the future (separate issues will be created). 

Additional PTM types will be introduced.
Some flanking mutations will be motif breaking or motif inducing (the MIMP algorithm results).

**Comment by reimand0** [comment]
Needle heads are currently very small (for example EGFR protein). In default zoom level they should be alwavs visible so that the user can see which mutations affect PTM sites. also. Let's make needle lines always in the same thickness in standard zoom level 

if mutations are overlapping too much near certain heights we could add "jiggle" such that the height of the needle is actual_height +/- small random number. Not sure if it helps, maybe worth considering.

**Comment by krassowski** [comment]
I finally tackled this in 218f656550edb164641502532d13f092b9a03157. I based on the idea of 'jiggling'. First of all we have small numbers on heads which tells user if there are more than one needle heads in this specific place. Secondly when user hovers mouse over such needle head, then the heads from the same position & value are being set in a row, so then user should be able to display tooltips for them. It makes big usability step (since all data are accessible in the plot) although there are minor implementation issues -  I will try to get over them in next few commits.
