### ISSUE TITLE
needles overlapping with filters box not accessible

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#45]
I would like to click on the mutation V600E in the BRAF protein. The filters menu pops up instead. We should probably move this menu elsewhere. 

It also needs to be changed - add filtering by cancer types and PTM types. These changes are documented in other Issues.

https://rl-db.oicr.on.ca/protein/show/NM_004333

Thanks!

**Comment by krassowski** [comment]
Will making the filter's box draggable resolve this issue?

**Comment by reimand0** [comment]
The box is likely growing, so maybe better move it above needle plot?

Jüri

**Comment by krassowski** [comment]
All right
