### ISSUE TITLE
headers and metainfo in mutation table

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#48]
New header names: 
- Pos, 
- Ref, 
- Mut, 
- PTM impact, 
- # PTMs \n affected, 
- Summary

Tooltips for header names
- Position of mutation in protein
- Reference amino acid residue in protein
- Mutated amino acid residue in protein
- Impact on closest PTM site
- Number of adjacent PTMs affected
- Mutation summary (click on + for more info)

**Comment by krassowski** [comment]
It's implemented and online. What do you think about keeping '# PTMs \n affected' in one line instead of two, or using other shorter name which would keep this in one line?

**Comment by reimand0** [comment]
yes, lets remove the line break. Also we dont need to show # - makes it
shorter and it is self explanatory anyway
