### ISSUE TITLE
table records with MIMP results not showing

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#51]
Looks like a bug in showing the mutation table. Network/rewiring mutations show no records

for example, TP53 P47S in ESP6500

https://rl-db.oicr.on.ca/protein/show/NM_000546?filter%5Bsources%5D%5Bcmp%5D=in&filter%5Bsources%5D=ESP6500&filter%5Bis_ptm%5D=None&fallback=True

**Comment by krassowski** [comment]
Disclaimer: no fix available for now since the code responsible for this behavior is not in repository yet (it's a result of work-in-progress changes and lack of testing environment). Although it might be good to keep this open until works with MIMP mutation wouldn't be finished.

**Comment by krassowski** [comment]
I have opened an issue in _bootstrap-tabe_ repository which is related to undesirable behavior of MIMP rows in version tested on server: https://github.com/wenzhixin/bootstrap-table/issues/2621

**Comment by reimand0** [comment]
Looks like the issue as been solved. Thanks for looking into this. Did
bootstrap-table team take action?

**Comment by krassowski** [comment]
No, I implemented a workaround for this. It still would be better if they were able to solve this, but since there is no reply from the team I am afraid even making a pull request won't help right now.

**Comment by reimand0** [comment]
OK. perhaps we will hear from them soon. Thanks for the workarounds.

**Comment by reimand0** [comment]
just to mention that this may be broken again - tooltips show MIMP logo but the table does not. 

https://rl-db.oicr.on.ca/protein/show/NM_001141980

**Comment by reimand0** [comment]
There is a network-rewiring event with closest site being Acetylation. With network-rewiring events we should show the site that that corresponds to the central S/T/Y site in the MIMP logo

![screen shot 2016-09-09 at 1 04 15 pm](https://cloud.githubusercontent.com/assets/19268349/18395749/0346bbfe-768e-11e6-8bad-c6fede5bc1fe.png)

**Comment by reimand0** [comment]
Also, maybe it is worth listing all PTM sites within +-7 residues of the mutation, rather than the closest one? It is usually just a few ones

**Comment by krassowski** [comment]
This just made me find another issue and it seems to be more serious bug.. I guess we should show all MIMP logos for a given mutation, not just one, should we?

Please, compare: https://rl-db.oicr.on.ca/protein/show/NM_000546#151R with following grep results:
```
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.89913618	0.03714978	-4.597114	MAPK3	MAPK_ERK1	252	0.9395799	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.94600270	0.03681019	-4.683667	CDK1	CDK_CDC2	373	0.9206202	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.89107808	0.03219058	-4.790841	MAPK1	MAPK_ERK1	328	0.9195478	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.52482646	0.14112542	-1.894863	GSK3B	GSK	156	0.8872093	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.84655707	0.10471603	-3.015125	CDK4	CDK	 45	0.8814233	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.60796506	0.25038178	-1.279859	CDK7	CDK	 27	0.8770811	loss
NM_000546	P151R	150	 1	VQLWVDSTPPPGTRV	VQLWVDSTRPPGTRV	0.92722297	0.04503945	-4.363655	CDK2	CDK_CDC2	444	0.8718904	loss
NM_000546	P151R	149	 2	PVQLWVDSTPPPGTR	PVQLWVDSTRPPGTR	0.10970934	0.47166236	 2.104068	PRKCG	PKC_Alpha	 40	0.8552339	gain
```
I though that the MIMP logos are generated once per mutation (little bit silly assumption) so it looks that in current version the system / import skips a lot of information. Also it implies that we cannot show just 'gain' or 'loss' in a column since it all depends on which kinase we are dealing with.

@reimand0 if you can confirm this, please open another issue and keep this close, because the matter has changed and it would be a great help for me to see issues grouped by relevant titles in the bugtracker :)
