### ISSUE TITLE
MIMP multiple logos

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#52]
As discussed, we currently only show the first MIMP logo. We instead should show the best logo per gain and the best logo per loss. If only one type is present, then we should show the best for that type. We should choose the logo(s) with the highest probability score.

Under the loss logo, we could show a list of other kinases that also had losses with lower probability scores. Same for the gain logo. 

In other places of the protein view, like the table and the tooltip, we should indicate if both loss and gain are predicted in the network-rewiring mutation.

**Comment by krassowski** [comment]
Does column named `prob` in MIMP data represent probability?

**Comment by reimand0** [comment]
Yes if I remember correctly. It should range between 0.85 and 1.0.
