### ISSUE TITLE
PTM mutation switch

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#6]
we should have a global switch to show all mutations or only PTM mutations. This should be reflected in the protein view, network view and mutations table.

**Comment by krassowski** [comment]
As for e2a14a7aa6b214d403d7506b974b5bd084f73d70 the issue could be closed. After 704f866c0cc31782e7ef625a3ecb460341a1b967 it is also scripted with JS. How should I improve this feature later? Should be there one switch (filter) for all PTM related mutations and mutations laying around to PTM sites or should there be multiple switches (filters) for those?

**Comment by reimand0** [comment]
we should have
 - all mutations
 - PTM mutations (direct and flanking)
 - direct PTM mutations only

**Comment by reimand0** [comment]
also for future purposes
- network-rewiring PTM mutations only (from MIMP tool)

**Comment by reimand0** [comment]
opening this topic again. 

There are two main filters:
1. show "all mutations" vs "PTM mutations only"
2. what dataset do we show. Only one dataset is active at one time, of the following (in this order):
- TCGA (cancer)
- ClinVar (disease)
- ESP6500 (population)
- 1000 Genomes (population)

These filters should be active (and available for changing) in protein view, in search page and also in network view.

**Comment by reimand0** [comment]
i think we can close this one due to developments under other issues. If you agree, please go ahead and close.

**Comment by krassowski** [comment]
What about filtering in search page (it's the only thing not implemented from this discussion)?

**Comment by reimand0** [comment]
yes, it is a good idea to add filters to the search page.

**Comment by reimand0** [comment]
following up on this: 
in the proteins search page, we should have a checkbox [x] "show only proteins with PTM mutations"
https://rl-db.oicr.on.ca/search/proteins

**Comment by krassowski** [comment]
I added the checkbox. If it's active it checks if preferred isoforms of a gene has at least one PTM mutation and keeps only genes with such preferred isoforms.
