### ISSUE TITLE
network visualisation #4 (represent mutation count with gradient) 

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#60]
4. we should use color gradient from white to red to denote how many mutations each protein has, and how many mutations each site has. this gradient should change when a cancer type is selected.

**Comment by krassowski** [comment]
I implemented this, right now for kinases only. Light-blue background means that we do not have a protein associated with given kinase, hence we cannot say how many know mutation it has. What to do about groups? Should they have a mutations count calculated as an average from associated kinases, or none?

I think that the scale for sites should be separate, right? Should we use the same colors then?

**Comment by krassowski** [comment]
Also we should change highlighting color - it has too little contrast after using the scale with white on one end. If you have any preferences about the color, let me know, I will test out some combinations.

**Comment by reimand0** [comment]
Let's not add mutations to kinase groups. These groups do not have very
precise definitions so any mutation counts are risky.

Site color scales - perhaps % of total mutations in that protein. We may
try to use the same color as kinases and central protein.
