### ISSUE TITLE
network visualisation #5 (tooltips with details)

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#61]
5. we should use the same types of tooltips to display mutations in genes in the network. count of mutations in cancer types, types of mutations (PTM, non-PTM, network-rewiring), maybe something else I forgot.

**Comment by krassowski** [comment]
Short question: opening kinase "protein view" vs sticking tooltips: which behaviour should be bound to "click on node" action? Maybe we can use double click for opening the protein view? Maybe we don't wont sticking tooltips (but then copying text from them would be impossible).

**Comment by reimand0** [comment]
If we have sticky tooltips with single click, then having a link in tooltip
for Protein View will solve the problem.
