### ISSUE TITLE
exporting images

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#63]
Is there a way to create PDF snapshot images of sequence view and protein network view?

**Comment by krassowski** [comment]
I implemented two ways to do this:

* as export to SVG file (of sole visualisation; without any additions like tooltips, headers or footers)
* simple 'print' which always can be used to save as PDF file - unnecessary buttons, links, etc. are discarded but still this is a field for improvement (we can choose different element to appear / hide).

It is possible to rewrite the SVG contents to PDF without printing, though it won't be an easy task - probably we would have to send user-modified code (ie. modified by interactions like dragging, clicking etc.) to server where special converter will be running. It's also possible to do this completely on user-side, but it would be much harder to implement and maintain (especially to support different browsers).

One thing which would be nice to have is some concise box describing all active filters - one solution is to just change styling of the existing one while printing.

**Comment by reimand0** [comment]
This comment applies to printing and also more generally - we should have evidence of currently selected filters. For example, near the %disordered text under the protein domains visualisation, we should have more information about current settings:
- which dataset selected
- which PTM sites selected (or all)
- all mutations shown or only PTM-related
- any subtypes in dataset selection (eg cancer type specific mutations)
- other filters active

Same for network view.
