### ISSUE TITLE
reducing MIMP tooltips

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#67]
currently:

Best loss:
[motif logo]
Site: 150: T (phosphorylation)
Probability: 0.93958
Effect: loss
Position in motif: 1
6 other annotations with predicted 'loss' effect exists.
Those include predicted interactions with:
CDK1 (probability: 0.92062)
MAPK1 (probability: 0.919548)
GSK3B (probability: 0.887209)
CDK4 (probability: 0.881423)
CDK7 (probability: 0.877081)
CDK2 (probability: 0.87189)

New candidate description:

Best loss: KIN1 at T150 (p=0.940)
[motif logo]
Position in motif: 1
There are 6 other predicted losses:
CDK1 (p=0.921), MAPK1 (p=0.920), GSK3B (p=0.887), CDK4 (p=0.881), CDK7 (p=0.877), CDK2 (p=0.872)

**Comment by krassowski** [comment]
Currently implemented version is slightly different than specified. I expanded 'p' in the first row to 'probability' to have at least one place where the full form is used, and left site below the logo. Is that good enough or should I change something?

**Comment by reimand0** [comment]
I made a few additional changes here:

PTM type: network-rewiring
Ref residue: R
Position: 
Alt residue: W
Count: 23
Closest affected sites:
284T (phosphorylation)
MIMP:
Best loss: AURKB (probability = 0.893)


PTM type: network-rewiring
Mutation 282 R->W
Mutation count: 23
Closest affected sites:
284T (phosphorylation)
MIMP prediction of mutation impact:
Best loss: AURKB (probability p=0.893)

**Comment by krassowski** [comment]
What about current state (I've implemented the new changes)?

**Comment by reimand0** [comment]
Looking great, thanks!
