### ISSUE TITLE
expand to all sites per per mutation

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#68]
currently we have only the closest PTM site per every mutation. We should add all sites near a mutation, and add associated kinases/enzymes in brackets if these exist.

**Comment by krassowski** [comment]
Should the columns with kinases also display kinases from all effected sites, not only from the closest ones?

**Comment by reimand0** [comment]
Hi Michal, yes! Thanks for noting that and sorry for late response.
