### ISSUE TITLE
colors and SNV counts in network view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#71]
Looks like mutation counts of kinases are overestimated. For example, ATM in network view of TP53 is very bright red and shows 2027 mutations, which probably incorrect.

https://rl-db.oicr.on.ca/network/show/NM_000546
https://rl-db.oicr.on.ca/protein/show/NM_000051

**Comment by krassowski** [comment]
Actually those are sums of mutations from all sources (unless filters are implemented). Look at ClinVar - there are **a lot** of mutations here. Not sure about actual number, but it's plausible for me. Does it sounds more reasonable now?

**Comment by reimand0** [comment]
I guess it adds up when considering all data sources. As i mentioned in another recent issue, adding dataset filters may resolve these counts problems.

**Comment by krassowski** [comment]
I think that we can close this issue now, when the filters are already implemented, can't we?

**Comment by reimand0** [comment]
yes, looks good
