### ISSUE TITLE
hierarchical filtering of protein domains

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#73]
I received a reply from Interpro with a hierarchy of domains. We can use this to reduce the number of domains we show. It does not cover all domains but we can reduce some of it. It would be good to know how many domains can we remove from our annotations with this strategy. 

If a protein position has both lower-level and higher-level domain, we should choose only higher-level domain to show. If the higher-level domain is smaller than the lower-level domain by small amount (maybe 10%?), we should remove the extra 10% of residues of that lower-level domain. 

ftp://ftp.ebi.ac.uk/pub/databases/interpro/ParentChildTreeFile.txt

**Comment by krassowski** [comment]
After checking out following page: http://www.ebi.ac.uk/interpro/protein/P04637 and comparing it to https://rl-db.oicr.on.ca/protein/show/NM_000546 it seems to me that one important thing would be to separate domains from families (now it's all mixed up) and then maybe follow the same rules as the team from EBI has chosen; it looks like they are choosing just the widest range from given domain tree to represent it (although they don't have any labels visible by default till user hovers his mouse over the "domain").

**Comment by reimand0** [comment]
yes, this sounds like a good idea. thanks
