### ISSUE TITLE
colors of network edges

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#74]
In the network view, we could use colors to show edges between sites (squares) and kinases where MIMP mutations have been annotated. 

For losses, we can use a red dashed line and increase width of edge if there are more mutations. 

For gains, I am not certain we should do it, because it would create a new kinase in the network which is only a prediction and not supported by the data.

**Comment by krassowski** [comment]
This is ready

**Comment by reimand0** [comment]
I think we should use a thicker dashed line to make sure it is visible. the current difference is quite subtle.

**Comment by krassowski** [comment]
I've made those thicker by 50%. The difference between edges from `269 S` and `211 T` in TP53 is more apparent. Is that good enough or should be thicker?

**Comment by reimand0** [comment]
looks good, thanks
