### ISSUE TITLE
network view - site colors

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#75]
As discussed, we should review site coloring in networks. I propose these follow the same color logic as the circles on top of needles. 

gray - no mutations
yellow - distant mutations
orange - proximal mutations
red - MIMP mutations
darkred - direct mutations

In case of multiple mutations, the color with the higher priority should dominate (increasing priority above).

Let's try to increase the size of the box according to mutation count.

**Comment by krassowski** [comment]
This is now implemented too. I think that another way of doing this would be to have thick borders around sites in appropriate colors and the interior left in white - this would improve contrast and consistency (although it could become visually more complicated).

**Comment by reimand0** [comment]
looks good, thanks
