### ISSUE TITLE
Migrate to OICR server

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#8]

**Comment by krassowski** [comment]
As there is currently only the issue of allowing the access to application over the public network, maybe it could be possible to use X forwarding in the meanwhile? I do not know excatly how to configure this, but once configured (and assuming there is a browser with graphical interface installed) it could be ran just by `ssh -Y` and I would be able to test the application that way. Is that an option or the server's software is command-line only (or configuration would take to much effort)?

**Comment by reimand0** [comment]
Sorry, I don't know answers to these questions right away. What does
helpdesk say? I asked them to explain remote access to me but I am still
waiting.

**Comment by krassowski** [comment]
Finished with 3408a79f7bae0f8493e49fec3cd42591e7c57167, along with setting the configuration of Apache2, wsgi_mod and setting app.wsgi. Closing for now.
