### ISSUE TITLE
progress bar / rotating circle

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#80]
we should add a progress bar or a rotating circle of points to indicate when the website is loading. This will help users be more patient and understand when things are in progress

**Comment by krassowski** [comment]
The rotating circle is in, in the bottom-right corner of screen. It is shown on every page (usually disappears rapidly). It has a very good effect on the network view, but provides only limited improvements to the protein view: I did not switched to AJAX retrieval here yet (it will be more complicated and there is some hard design decision: should we render the mutations table server- or client-side). Nonetheless, I think that we can close this issue.
