### ISSUE TITLE
compact filters box

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#81]
Let's attempt to make the filters box more compact. Can we fit the filter next to one another instead of top to bottom?

The goal is to see the main visualisation (needleplot or network) on a relatively small screen without needing to scroll down. 

Another aspect of this - instead of dataset dropdown menu, can we use radio buttons? The advantage of this approach is that this important selection is always visible. Currently non-cancer researchers are at a disadvantage because they need to find a switch that is hidden in a dropdown menu.

changes for the filter groups and labels:

Active - remove this
Source - Mutation dataset - let's try a radio button
2nd filter - Cancer type / ethnicity / clinical significance
Available - remove this
PTM mutations - replace with a checkbox - show only PTM mutations
Site type - type of PTM site

**Comment by krassowski** [comment]
I have implemented changes we discussed during our call on Friday. The filters are still one under another (not side by side) since I am not sure if we decided if this behavior is still favored (taking into account the expanded bar with radio buttons used for dataset selection).

**Comment by reimand0** [comment]
Looks good!

1. let's remove the word Filters.
2. move dropdown for "cancer types" to the right of the bulletpoints for
"Mutation dataset"
3. remove words Cancer type / ethnicity / Clinical significance.
4. instead of above, make these to be the first, default value in the
dropdown menu, that is All cancer types, All ethnicities  / All clinical
significance classes
5. Expand site type into bulletpoints similarly to Mutation dataset.
Replace "Site" with "PTM site"

**Comment by krassowski** [comment]
I've implemented changes listed above. Is everything right?

**Comment by reimand0** [comment]
looks good, thanks!
