### ISSUE TITLE
PTM site filter

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#86]
found this inconsistency:

1. activate filter "PTM mutations only"
2. select PTM site type, e.g. methylation
3. observe a lot of gray needles that should not be shown.

**Comment by krassowski** [comment]
I understand that the behavior returning mutations in nearby of _any_ PTM site, not only of those selected in filters panel might be misleading for the end-user. I have removed this inconsistency.

**Comment by reimand0** [comment]
thanks!
