### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#89]
we should create a module to enable users to send us comments and feedback. the general form would be located at the Contact-us page that also has a CMS component. The same module could be re-used in various parts of our page. For example, a user may want to leave feedback at a specific mutation or gene. Then the email would come with some additional information pre-filled.

**Comment by krassowski** [comment]
Just to recap implementation:

- links in "contact boxes" pass arguments to pre-fill input fields in URL, e.g.:
`https://activedriverdb.org/contact_us?feature=protein&title=TP53%20-%20NM_000546`
- list of recipients is located in `config.py` file ([CONTACT_LIST](https://github.com/reimandlab/Visualisation-Framework-for-Genome-Mutations/blob/master/website/example_config.py#L37) variable)
- contact form can be inserted on any CMS page. It is inserted the same way as stats variables, i.e. with double curly braces: `{{ contact_form }}`. I added it manually to `/contact_us/` page.
- currently the default settings of [flask-mail](https://pythonhosted.org/Flask-Mail/) are used (so server=localhost, port=25, etc). Those can be changed adding appropriate variables to `config.py` file.
