### ISSUE TITLE
mapping DNA to protein

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#9]
We should start with mapping DNA-level coordinates to protein coordinates. I have precomputed a table with all single nucleotide variants that correspond to PTM site mutations available below

http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1004919
S1 File and S2 File. 

I will compute a similar larger table for all SNVs that change protein sequence (work in progress). 

The goal is the following - person comes in with set of variants at DNA level (chr1 12345678 A C). We will look this up in the table and return PROT1 345 S Q (corresponding protein variant) and say whether this is a PTM variant or non PTM variant. 

This table needs rapid indexing because it is quite large. Also people may have a large number of variants to test. We want this to be as interactive as possible, but maybe we need to implement a offline calculation in the future.

**Comment by krassowski** [comment]
Closing this issue as described functionality is implemented for a long time and discussion about various nuances of implementation happens in other issues.
