### ISSUE TITLE
CMS - removing of pages

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#90]
at the URL https://rl-db.oicr.on.ca/list_pages/, removal of pages does not work.

https://rl-db.oicr.on.ca/remove_page/introduction

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by krassowski** [comment]
Ok, I can confirm: the problem is foreign key constraint on (menu entries, page) and lack of appropriate cascade defined for those tables.

**Comment by reimand0** [comment]
also, I noted a similar issue when I changed the URL of a particular page
that I was editing. After clicking to save changes, an error was thrown.
Perhaps this happened because the previous page no longer existed.

**Comment by krassowski** [comment]
Also fixed now. Thank you for giving very precise reproduction information for errors you encountered, it helps a lot :)
