### ISSUE TITLE
incorrect cancer types in API

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#91]
Seems like tissue types provided by JSON are shown incorrectly. Marta analysed thousands of breast cancer mutations and they were mapped to various types (ovarian, brain, lung). I tried a few examples and arrived at the same conclusion. 

https://rl-db.oicr.on.ca/chromosome/mutation/chr10/116247760/T/C

This mutation is from the TCGA MAF file of breast adenocarcinoma. 

ABLIM1	0	-	37	10	116247760	116247760	+	Missense_Mutation	SNP	T	T	C			TCGA-A1-A0SB-01A-11D-A142-09	TCGA-A1-A0SB-10B-01D-A142-09

The barcode has A1 in the 2nd position, meaning it is a breast cancer sample according to the table from TCGA https://wiki.nci.nih.gov/pages/viewpage.action?pageId=29557833

Does this affect only JSON or other parts of  the database?

**Comment by krassowski** [comment]
It would be very serious bug. OK, so we have a row:
```10	116247760	116247760	T	C	exonic	ABLIM1	.	nonsynonymous SNV	ABLIM1:NM_006720:exon3:c.A50G:p.H17R,ABLIM1:NM_001003407:exon8:c.A818G:p.H273R,ABLIM1:NM_001003408:exon8:c.A818G:p.H273R,ABLIM1:NM_002313:exon8:c.A998G:p.H333R	comments: Ovarian serous cystadenocarcinoma;TCGA-A1-A0SB-01A-11D-A142-09;ABLIM1```
in our `TCGA_muts_annotated.txt` file.

If I understand correctly, I assumed wrongly that the annotation comment "Ovarian serous cystadenocarcinoma;TCGA-A1-A0SB-01A-11D-A142-09;ABLIM1" indicates that a given mutation is related to cancer type "Ovarian serous cystadenocarcinoma" BUT instead I should check the code from sample id, yes?

I'm terribly sorry for that, but I think it was quite tempting to assume the name from the comment field indicates cancer type - life would be so easy ;)

**Comment by reimand0** [comment]
Sorry, that was my mistake. Uploaded new file TCGA_muts_annotated.txt.gz
into dropbox.

**Comment by krassowski** [comment]
I have reimported the TCGA mutations data, it seems to be working.
