### ISSUE TITLE
data fields in API

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#92]
We should provide the gene symbol in the results in addition to RefSeq ID. 

Also let's add reference amino acid next to the mutated amino acid. For visual purposes I would move complex entries such as in_datasets towards the end of the results (to the right side of the entry)

**Comment by krassowski** [comment]
I implemented suggested changes. Is this good enough https://rl-db.oicr.on.ca/chromosome/mutation/chr10/116247760/T/C ?
