### ISSUE TITLE
gene lists for user browsing

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#93]
Let's simplify the example gene lists we provide for browsing:

for TCGA, you can find a good candidate list in the link below, in Supplementary Table 4, Column Cancer_type is PAN, sort by FDR. These are genes with significant phosphosite mutations in cancer. 
http://www.nature.com/articles/srep02651#supplementary-information

**Comment by reimand0** [comment]
for ClinVar, I don't have a very good idea of a gene list. I have analysed inherited disease mutations earlier with a proprietary database called HGMD. 

Would you be able to run the ActiveDriver method using the ClinVar dataset of mutations, longest isoforms of proteins and their disorder predictions, and all PTM sites we have? ActiveDriver R package and tutorial is available here:
http://individual.utoronto.ca/reimand/ActiveDriver/

**Comment by krassowski** [comment]
That sounds feasible, I will try to to this.

**Comment by krassowski** [comment]
Should I extract only gene names from the _Supplementary Table 4_ or also include additional data like `p-value`, `FDR`? Should I only get genes with `is_cancer_gene` equal to one or all genes with `PAN`?

**Comment by reimand0** [comment]
let's get all genes with "PAN". We could add a field for general Info to each gene in the list and then add information like FDR, known cancer gene to it. The info field would be somewhat different for Clinvar.

**Comment by krassowski** [comment]
Works in progress but here is an insight: https://rl-db.oicr.on.ca/gene/list/TCGA. All comments and suggestions are welcome.
